version: 0.0
os: linux
files:
  - source: /
    destination: /home/
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/run_file
      timeout: 300
      runas: root
